spring:
  application:
    name: board-for-workers
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/worker-board
      username: sa
      password: 1234

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  mustache:
    servlet:
      expose-session-attributes: true
server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  error:
    include-exception: true
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

cloud:
  ncp:
    end-point: test
    region-name: kr
    credentials:
      access-key: rDwa75mVrSUfMi5nA5D8
      secret-key: WdaHc8n46XzYPGqaDmMhE2GtPe57LkEME5Ihl9kS

changbi:
  mailsender:
    username: test
    password: test