-- MEMBER DATA IMPORT
INSERT INTO MEMBER (MEMBER_ID, MEMBER_EMAIL, MEMBER_REAL_NAME, MEMBER_NICK_NAME, MEMBER_PASSWORD, COMPANY, DEPARTMENT, ROLE, APPEND_DATE, UPDATE_DATE) VALUES (99, 'test@changbi.com', '김창비', '안녕하세요', '$2a$10$/Qg3qFcKuGDqlfKZJ0qy2OEEiPEHyu5y5MOzcNhUCbLmEAzQ19GAm', 'CHANGBI', 'HR', 'SUPER_ADMIN', NOW(), NOW());
INSERT INTO MEMBER (MEMBER_ID, MEMBER_EMAIL, MEMBER_REAL_NAME, MEMBER_NICK_NAME, MEMBER_PASSWORD, COMPANY, DEPARTMENT, ROLE, APPEND_DATE, UPDATE_DATE) VALUES (98, 'changbi@changbi.com', '안비창', '안비창', '$2a$10$/Qg3qFcKuGDqlfKZJ0qy2OEEiPEHyu5y5MOzcNhUCbLmEAzQ19GAm', 'CHANGBI_EDU', 'PUBLISHING', 'USER', NOW(), NOW());
INSERT INTO MEMBER (MEMBER_ID, MEMBER_EMAIL, MEMBER_REAL_NAME, MEMBER_NICK_NAME, MEMBER_PASSWORD, COMPANY, DEPARTMENT, ROLE, APPEND_DATE, UPDATE_DATE) VALUES (97, 'dev@changbi.com', '개발팀아무개', '😄', '$2a$10$/Qg3qFcKuGDqlfKZJ0qy2OEEiPEHyu5y5MOzcNhUCbLmEAzQ19GAm', 'MEDIA_CHANGBI', 'IT', 'USER', NOW(), NOW());


-- BOARD DATA IMPORT
INSERT INTO BOARD (BOARD_ID, BOARD_NAME, USE_YN, ATTACHMENT_ALLOW_YN, READ_ROLE, WRITE_ROLE, APPEND_DATE, UPDATE_DATE) VALUES (99, '자유게시판', TRUE, TRUE, 'GUEST', 'USER', NOW(), NOW());
INSERT INTO BOARD (BOARD_ID, BOARD_NAME, USE_YN, ATTACHMENT_ALLOW_YN, READ_ROLE, WRITE_ROLE, APPEND_DATE, UPDATE_DATE) VALUES (98, '공지사항', TRUE, TRUE, 'USER', 'ADMIN', NOW(), NOW());

-- POST DATA IMPORT
INSERT INTO POST (POST_ID, MEMBER_ID, BOARD_ID, POST_TITLE, POST_HEAD, POST_CONTENT, USE_YN, READ_COUNT, RECOMMEND_COUNT, APPEND_DATE, UPDATE_DATE) VALUES (99, 99, 99, 'TEST POST 01', 'GENERAL', 'test post', true, 0, 0, now(), now());