-- MEMBER DATA IMPORT
INSERT INTO MEMBER (MEMBER_ID, MEMBER_EMAIL, MEMBER_REAL_NAME, MEMBER_NICK_NAME, MEMBER_PASSWORD, COMPANY, DEPARTMENT, ROLE, APPEND_DATE, UPDATE_DATE) VALUES (1, 'test@changbi.com', '김창비', '안녕하세요', 'test1234', 'CHANGBI', 'HR', 'USER', NOW(), NOW());
INSERT INTO MEMBER (MEMBER_ID, MEMBER_EMAIL, MEMBER_REAL_NAME, MEMBER_NICK_NAME, MEMBER_PASSWORD, COMPANY, DEPARTMENT, ROLE, APPEND_DATE, UPDATE_DATE) VALUES (2, 'changbi@changbi.com', '안비창', '안비창', 'test1234', 'CHANGBI_EDU', 'PUBLISHING', 'USER', NOW(), NOW());
INSERT INTO MEMBER (MEMBER_ID, MEMBER_EMAIL, MEMBER_REAL_NAME, MEMBER_NICK_NAME, MEMBER_PASSWORD, COMPANY, DEPARTMENT, ROLE, APPEND_DATE, UPDATE_DATE) VALUES (3, 'dev@changbi.com', '개발팀아무개', '😄', 'test1234', 'MEDIA_CHANGBI', 'IT', 'USER', NOW(), NOW());


-- BOARD DATA IMPORT
INSERT INTO BOARD (BOARD_ID, BOARD_NAME, USE_YN, ATTACHMENT_ALLOW_YN, APPEND_DATE, UPDATE_DATE) VALUES (1, '자유게시판', TRUE, TRUE, NOW(), NOW());
INSERT INTO BOARD (BOARD_ID, BOARD_NAME, USE_YN, ATTACHMENT_ALLOW_YN, APPEND_DATE, UPDATE_DATE) VALUES (2, '공지사항', TRUE, TRUE, NOW(), NOW());