-- MEMBER DATA IMPORT
INSERT INTO MEMBER (MEMBER_ID, MEMBER_EMAIL, MEMBER_REAL_NAME, MEMBER_NICK_NAME, MEMBER_PASSWORD, COMPANY, DEPARTMENT, ROLE, APPEND_DATE, UPDATE_DATE) VALUES (99, 'test@changbi.com', '김창비', '안녕하세요', 'test1234', 'CHANGBI', 'HR', 'USER', NOW(), NOW());
INSERT INTO MEMBER (MEMBER_ID, MEMBER_EMAIL, MEMBER_REAL_NAME, MEMBER_NICK_NAME, MEMBER_PASSWORD, COMPANY, DEPARTMENT, ROLE, APPEND_DATE, UPDATE_DATE) VALUES (98, 'changbi@changbi.com', '안비창', '안비창', 'test1234', 'CHANGBI_EDU', 'PUBLISHING', 'USER', NOW(), NOW());
INSERT INTO MEMBER (MEMBER_ID, MEMBER_EMAIL, MEMBER_REAL_NAME, MEMBER_NICK_NAME, MEMBER_PASSWORD, COMPANY, DEPARTMENT, ROLE, APPEND_DATE, UPDATE_DATE) VALUES (97, 'dev@changbi.com', '개발팀아무개', '😄', 'test1234', 'MEDIA_CHANGBI', 'IT', 'USER', NOW(), NOW());


-- BOARD DATA IMPORT
INSERT INTO BOARD (BOARD_ID, BOARD_NAME, USE_YN, ATTACHMENT_ALLOW_YN, READ_ROLE, WRITE_ROLE, APPEND_DATE, UPDATE_DATE) VALUES (99, '자유게시판', TRUE, TRUE, 'GUEST', 'USER', NOW(), NOW());
INSERT INTO BOARD (BOARD_ID, BOARD_NAME, USE_YN, ATTACHMENT_ALLOW_YN, READ_ROLE, WRITE_ROLE, APPEND_DATE, UPDATE_DATE) VALUES (98, '공지사항', TRUE, TRUE, 'USER', 'ADMIN', NOW(), NOW());